### ISSUE TITLE
Spotify support in android app

### ISSUE THREAD

**Issue by francisdb** [TTFM-Labs/public#20] opened 2021-04-11 09:15 UTC
There is a slider for apple music in the app but nothing Spotify related? And I have no sound.

**Comment by t3dotgg** [comment] 2021-04-12 07:27
Actively in development, closing as this is a new feature not a bug https://trello.com/c/dA9KYO45/36-spotify-support-on-mobile

**Closed as completed by t3dotgg** 2021-04-12 07:27 UTC
