### ISSUE TITLE
Uncaught (in promise) DOMException: Failed to execute 'update' on 'MediaKeySession': Rejected with system code (44)

### ISSUE THREAD

**Issue by francisdb** [TTFM-Labs/public#8] opened 2021-04-03 07:33 UTC
But the music keeps on playing which is good (track transitions however not always clean)

```

CREATING NEW INSTANCE
index.8a7afdc4425925597987.js:195 Attempting to play track Open (Upside Down) [feat. Snowflake] [Full Length DJ Mix]
index.8a7afdc4425925597987.js:205 Complete now playing update {duration: 370.311, genre: "", id: "1278492799", musicProvider: "apple", title: "Open (Upside Down) [feat. Snowflake] [Full Length DJ Mix]", …}
index.8a7afdc4425925597987.js:205 checking if new track should be posted
index.8a7afdc4425925597987.js:205 posting new track
index.8a7afdc4425925597987.js:195 Queue set probably successful, output: Queue {_registry: {…}, _itemIDs: Array(1), _unshuffledIDs: {…}, _items: Array(1), _isRestricted: false, …}
index.8a7afdc4425925597987.js:195 Play succeeded with status undefined
9hwnd:1 Uncaught (in promise) DOMException: Failed to execute 'update' on 'MediaKeySession': Rejected with system code (44)
index.8a7afdc4425925597987.js:205 triggering play w/ skim
index.8a7afdc4425925597987.js:205 


CREATING NEW INSTANCE
index.8a7afdc4425925597987.js:195 Attempting to play track Running on Empty
index.8a7afdc4425925597987.js:205 Complete now playing update {duration: 476.328, genre: "", id: "1246756234", musicProvider: "apple", title: "Running on Empty", …}
index.8a7afdc4425925597987.js:205 checking if new track should be posted
index.8a7afdc4425925597987.js:205 posting new track
index.8a7afdc4425925597987.js:195 Queue set probably successful, output: Queue {_registry: {…}, _itemIDs: Array(1), _unshuffledIDs: {…}, _items: Array(1), _isRestricted: false, …}
index.8a7afdc4425925597987.js:195 Play succeeded with status undefined
15hwnd:1 Uncaught (in promise) DOMException: Failed to execute 'update' on 'MediaKeySession': Rejected with system code (44)
index.8a7afdc4425925597987.js:205 triggering play w/ skim
index.8a7afdc4425925597987.js:205 


CREATING NEW INSTANCE
index.8a7afdc4425925597987.js:195 Attempting to play track Follow Me (feat. Eurielle & Ryan Louder) [Mixed]
index.8a7afdc4425925597987.js:205 Complete now playing update {duration: 224.063, genre: "", id: "1468633878", musicProvider: "apple", title: "Follow Me (feat. Eurielle & Ryan Louder) [Mixed]", …}
index.8a7afdc4425925597987.js:205 checking if new track should be posted
index.8a7afdc4425925597987.js:205 posting new track
index.8a7afdc4425925597987.js:195 Queue set probably successful, output: Queue {_registry: {…}, _itemIDs: Array(1), _unshuffledIDs: {…}, _items: Array(1), _isRestricted: false, …}
index.8a7afdc4425925597987.js:195 Play succeeded with status undefined
index.8a7afdc4425925597987.js:205 triggering play w/ skim
index.8a7afdc4425925597987.js:205 


CREATING NEW INSTANCE
index.8a7afdc4425925597987.js:195 Attempting to play track Unacceptable (feat. Ophidian)
index.8a7afdc4425925597987.js:205 Complete now playing update {duration: 360.973, genre: "", id: "1002002929", musicProvider: "apple", title: "Unacceptable (feat. Ophidian)", …}
index.8a7afdc4425925597987.js:205 checking if new track should be posted
index.8a7afdc4425925597987.js:205 posting new track
index.8a7afdc4425925597987.js:195 Queue set probably successful, output: Queue {_registry: {…}, _itemIDs: Array(1), _unshuffledIDs: {…}, _items: Array(1), _isRestricted: false, …}
index.8a7afdc4425925597987.js:195 Play succeeded with status undefined
16hwnd:1 Uncaught (in promise) DOMException: Failed to execute 'update' on 'MediaKeySession': Rejected with system code (44)
```

**Comment by francisdb** [comment] 2021-04-03 07:35
that uncaught exception repeats 4 to 16 times

> **16**hwnd:1 Uncaught (in promise)...

**Comment by t3dotgg** [comment] 2021-04-03 21:31
This is the same issue as the 15 minute timeout. Caused by Widevine failing to reauth. The repetition of the error is because I create a new instance of MusicKit on every track to avoid the timeout

Closing in favor of https://github.com/TTFM-Labs/public/issues/7

**Closed as completed** 2021-04-03 21:31 UTC
